import type { Metadata } from "next";
import { Source_Sans_3, Gorditas } from 'next/font/google';
import "./globals.css";

const sourceSans = Source_Sans_3({subsets: ["latin"], weight: ["400", "500", "700", "900"], variable: "--font-source-sans"});
const gordita = Gorditas({subsets: ["latin"], weight: ["400", "700"], variable: "--font-gordita"});

export const metadata: Metadata = {
  title: "GroceryMart - Grocery Store App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${sourceSans.variable} ${gordita.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
